core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path("",include("showroom.urls")),
    path("admin/", admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

showroom/urls.py
from django.urls import path
from . import views

app_name = "showroom"

urlpatterns = [
    path('', views.showroom_view, name='showroom'),

    path('team', views.team_list, name='team_list'),
    path('member/<int:member_id>/', views.member_detail, name='member_detail'),

    path('brands', views.brand_list_view, name='brands_list'),
    path('<int:brand_id>', views.brand_models, name='brand_models'),

    path('models', views.models_list_view, name='models_list'),
    path('model-detail/<int:model_id>', views.model_detail, name='model_detail'),

]

showroom/models.py
from django.db import models

# Create your models here.
class Showroom(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=300)
    contact = models.CharField(max_length=20)
    email = models.EmailField(max_length=100,unique=True)

    def __str__(self):
        return self.name

class Team(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(null=True, blank=True)
    role = models.CharField(max_length=100)
    contact_number = models.CharField(max_length=20)
    email = models.EmailField()
    showroom = models.ForeignKey(Showroom,on_delete=models.CASCADE,related_name="team")

    def __str__(self):
        return self.name
    

class Brands(models.Model):
    class Meta:
        verbose_name_plural = "Brands"
    name = models.CharField(max_length=100)
    logo = models.ImageField(null=True, blank=True)
    country = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name



class Engine(models.Model):
    ENGINE_TYPES = [
        ('Petrol', 'Petrol'),
        ('Diesel', 'Diesel'),
        ('Electric', 'Electric'),
        ('Hybrid', 'Hybrid'),
        # Add more engine types as needed
    ]
    engine_type = models.CharField(choices=ENGINE_TYPES, max_length=20)
    displacement = models.CharField(max_length=20)
    power = models.CharField(max_length=50)
    engine_number = models.CharField(max_length=20,unique=True)

    def __str__(self):
        return self.engine_type
    
class Features(models.Model):
    class Meta:
        verbose_name_plural = "Features"
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    

class Models(models.Model):
    class Meta:
        verbose_name_plural = "Models"
    name = models.CharField(max_length=100)
    brand = models.ForeignKey(Brands, on_delete=models.CASCADE, related_name='models')
    year = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    image = models.ImageField(null=True, blank=True)
    engine = models.ForeignKey(Engine,on_delete=models.SET_NULL, null=True, blank=True, related_name="models")
    features = models.ManyToManyField(Features,blank=True,related_name="models")

    def __str__(self):
        return self.name
    

showroom/views.py
from django.shortcuts import render
from .models import *
# Create your views here.

def showroom_view(request):
    showroom = Showroom.objects.first()
    # models = Models.objects.all()
    models = Models.objects.order_by('?')[:3] #randomly picks 3 models from the database, 
    brands = Brands.objects.order_by('?')[:3]

    return render(request,'showroom/home.html',{'showroom':showroom,'models':models,'brands':brands})

def brand_list_view(request):
    brands = Brands.objects.all()
    return render(request,'showroom/brands_list.html',{'brands':brands})

def brand_models(request,brand_id):
    # models = Models.objects.get(brand = brand_id)
    brand = Brands.objects.get(id= brand_id)
    models = brand.models.all()

    return render(request,'showroom/models_list.html',{'models':models})

def models_list_view(request):
    models = Models.objects.all()
    return render(request,'showroom/models_list.html',{'models':models})

def model_detail(request,model_id):
    model = Models.objects.get(id = model_id)
    return render(request,'showroom/model_detail.html',{'model':model})

def team_list(request):
    team = Team.objects.all()
    return render(request,'showroom/team_list.html',{'team':team})

def member_detail(request,member_id):
    member = Team.objects.get(id = member_id)
    return render(request,'showroom/member_detail.html',{'member':member})

showroom/templates/showroom/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {%load static %}
    <title>{% block title %}Home{% endblock %}</title>
    
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{%url 'showroom:showroom' %}">{%block navbar-brand %} Auto Hub {%endblock%}</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
             
              <li class="nav-item">
                <a class="nav-link" href="{%url 'showroom:brands_list' %}">Brands</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{%url 'showroom:models_list' %}">Models</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{%url 'showroom:team_list' %}">Team</a>
              </li>
              <!-- Add more navigation links as needed -->
            </ul>
          </div>
        </div>
      </nav>
      <div class="container">
        {% block content %}
        {% endblock %}
      </div>

      <footer class="bg-dark text-white text-center py-3 footer">
        <div class="container">
          <p>&copy; {% now "Y" %} Auto Hub. All rights reserved.</p>
          <p><a class="text-white" href="">Privacy Policy</a> | <a class="text-white" href="">Terms of Service</a></p>
          <!-- Add more footer links or content as needed -->
        </div>
      </footer>
      <style>
        body {
            background-color: lightgray;
            padding-bottom: 60px; /* Adjust this value to ensure content does not get hidden behind the footer */
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            height: 60px; /* Set the height of your footer */
            background-color: #343a40; /* Replace with your preferred footer background color */
            color: #fff; /* Replace with your preferred footer text color */
            padding-top: 20px;
        }
    </style>
</body>
</html>

showroom/templates/showroom/brands_list.html
{%extends "showroom/base.html" %}

{%block title %} Brands {%endblock%}
{%block content %}
<div class="container">
    <div class="row">
        {% for brand in brands %}
        <div class="col-md-4 mb-4">
            <div class="card h-100 " style="margin-top: 20px;">
                <img src="{{ brand.logo.url }}" class="card-img-top" alt="{{ brand.name }}" style="height: 150px;">
                <div class="card-body">
                    <h5 class="card-title">{{ brand.name }}</h5>
                    <p class="card-text">{{ brand.description }}</p>
                        <div class="col-12">
                            <a href="{% url 'showroom:brand_models' brand.id %}" class="btn btn-primary mb-3">View models in this brand</a>
                        </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{%endblock%}

showroom/templates/showroom/home.html
{% extends "showroom/base.html" %}


{%block content %}

<h1>Available Models</h1>
<div class="container">
    <div class="row ">
        <div class="text-end">
        <div class="col-12">
            <a href="{% url 'showroom:models_list' %}" class="btn btn-primary mb-3">Show All</a>
        </div>
        </div>
    </div>
    <div class="row">
        {% for model in models %}
        <div class="col-md-4 mb-4">
            <div class="card h-100">
                <img src="{{ model.image.url }}" class="card-img-top" alt="{{ model.name }}" style="height: 250px;">
                <div class="card-body">
                    <h5 class="card-title">{{ model.name }}</h5>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<h1>We deal in the following Brands</h1>
<div class="container">
    <div class="row ">
        <div class="text-end">
        <div class="col-12">
            <a href="{% url 'showroom:brands_list' %}" class="btn btn-primary mb-3">Show All</a>
        </div>
        </div>
    </div>
    <div class="row">
        {% for brand in brands %}
        <div class="col-md-4 mb-4">
            <div class="card h-100">
                <img src="{{ brand.logo.url }}" class="card-img-top" alt="{{ brand.name }}" style="height: 150px;">
                <div class="card-body">
                    <h5 class="card-title">{{ brand.name }}</h5>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

showroom/templates/showroom/member_detail.html
{%extends "showroom/base.html" %}

{%block title %} Model - Detail {%endblock%}
{%block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2 mb-4">

        </div>
        <div class="col-md-8 mb-4">
            <div class="card h-100 " style="margin-top: 20px;">
                <img src="{{ member.image.url }}" class="card-img-top" alt="{{ model.name }}" style="height: 400px;">
                <div class="card-body">
                    <h5 class="card-title">{{ member.name }}</h5>
                    <p class="card-text">{{ member.role }}</p>
                    <strong><p class="card-text">Contact: {{ member.contact_number }}</p></strong>
                    <p class="card-text"><strong>Email:</strong> {{ member.email }}</p>                    

                    <div class="col-12">
                        <a href="{% url 'showroom:team_list'%}" class="btn btn-primary mb-3">Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

showroom/templates/showroom/model_detail.html
{%extends "showroom/base.html" %}

{%block title %} Model - Detail {%endblock%}
{%block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2 mb-4">

        </div>
        <div class="col-md-8 mb-4">
            <div class="card h-100 " style="margin-top: 20px;">
                <img src="{{ model.image.url }}" class="card-img-top" alt="{{ model.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ model.name }}</h5>
                    <p class="card-text">{{ model.brand }}</p>
                    <strong><p class="card-text">Price: {{ model.price }} Rs.</p></strong>
                    <p class="card-text"><strong>Description:</strong> {{ model.description }}</p>

                    <p class="card-text">Year: {{ model.year }}</p>
                    <ul> Engine: 
                    <li>Type: {{ model.engine.engine_type }}</li>
                    <li>displacement: {{ model.engine.displacement }}</li>
                    <li>Power: {{ model.engine.power }}</li>
                    </ul>

                
                    <ul> Features
                    {%for feature in model.features.all %}
                    <li>{{feature.name}}: {{feature.description}}</li>
                    {%endfor%}
                    </ul>

                    <div class="col-12">
                        <a href="{% url 'showroom:models_list'%}" class="btn btn-primary mb-3">Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

showroom/templates/showroom/models_list.html
{%extends "showroom/base.html" %}

{%block title %} Models {%endblock%}
{%block content %}
<div class="container">
    <div class="row">
        {% for model in models %}
        <div class="col-md-4 mb-4">
            <div class="card h-100 " style="margin-top: 20px;">
                <img src="{{ model.image.url }}" class="card-img-top" alt="{{ model.name }}" style="height: 200px;">
                <div class="card-body">
                    <h5 class="card-title">{{ model.name }}</h5>
                    <p class="card-text">{{ model.brand }}</p>
                    <strong><p class="card-text">{{ model.price }}</p></strong>

                        <div class="col-12">
                            <a href="{% url 'showroom:model_detail' model.id %}" class="btn btn-primary mb-3">View Details</a>
                        </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{%endblock%}

showroom/templates/showroom/team_list.html
{%extends "showroom/base.html" %}

{%block title %} Team {%endblock%}
{%block content %}
<div class="container">
    <div class="row">
        {% for member in team %}
        <div class="col-md-4 mb-4">
            <div class="card h-100 " style="margin-top: 20px;">
                <img src="{{ member.image.url }}" class="card-img-top" alt="{{ member.name }}" style="height: 250px;">
                <div class="card-body">
                    <h5 class="card-title">{{ member.name }}</h5>
                    <strong><p class="card-text">{{ model.role }}</p></strong>

                        <div class="col-12">
                            <a href="{% url 'showroom:member_detail' member.id %}" class="btn btn-primary mb-3">View Details</a>
                        </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{%endblock%}